const STORAGE_KEY = "deliverykit:tracked-delivery-ids";
const MAX_IDS = 100;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isDeliveryId(value: string) {
  return UUID_PATTERN.test(value);
}

export function parseDemoDeliveryIds(contents: string): string[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(contents);
  } catch {
    throw new Error("This file is not valid JSON.");
  }
  if (
    typeof parsed !== "object" ||
    parsed === null ||
    !("format" in parsed) ||
    parsed.format !== "deliverykit-demo-v1" ||
    !("deliveryIds" in parsed) ||
    !Array.isArray(parsed.deliveryIds) ||
    parsed.deliveryIds.length === 0 ||
    parsed.deliveryIds.length > MAX_IDS ||
    !parsed.deliveryIds.every((id: unknown) => typeof id === "string" && isDeliveryId(id))
  ) {
    throw new Error("Select a demo ID file generated by the seed script (up to 100 IDs).");
  }
  return parsed.deliveryIds;
}

export function trackedDeliveryIds(): string[] {
  try {
    const parsed: unknown = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "[]");
    return Array.isArray(parsed)
      ? parsed
          .filter((id): id is string => typeof id === "string" && isDeliveryId(id))
          .slice(0, MAX_IDS)
      : [];
  } catch {
    return [];
  }
}

export function trackDeliveryIds(ids: string[]) {
  const next = [...new Set([...ids.filter(isDeliveryId), ...trackedDeliveryIds()])].slice(
    0,
    MAX_IDS,
  );
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
  } catch {
    // A blocked or full storage area should not block delivery requests.
  }
  return next;
}
